import Head from 'next/head';
type TitleProps = {
  title: string;
};
export default function Seo({ title }: TitleProps) {
  return (
    <Head>
      <title>{title} | Chatter</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
